# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4aa299138673210065e50a5fb7c6fe7db156d19878c891c8117601d35dd57f9cbaa0567e94749b33e89a59a26e6ceaf4706b61110d49d4534ad12856b62d90e4

test:
  secret_key_base: 5ae6fde49e6c34239b05847b1bf93eec33d8ad5ecf3b72fbd893f0427ee16c098f865b773ad6cab8d22f3f344787ef90e2316cb00b2e69a41456d37bdefbc54f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
